---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure Apache is installed.
  apt: "name={{ item }} state=installed"
  with_items: apache_packages

#- name: Make project root directory
#  file: path=servername: "test1.com", documentroot:

- name: test
  file: path="{{ apache_vhosts[0].documentroot }}{{ apache_vhosts[0].servername }}" state=directory
  tags: t1